In [56]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score

In [65]:
df=pd.read_csv("https://frenzy86.s3.eu-west-2.amazonaws.com/python/data/cars.csv")
df

,name,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...
887,Ta,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,2014,"1,60,000",Petrol,NaN

In [69]:
df=df[df["Price"]!="Ask For Price"]

In [70]:
df['Price'] = df['Price'].astype(str).str.replace(',', '', regex=False)

In [82]:
df['Price'].astype(int)

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
886    300000
888    260000
889    390000
890    180000
891    160000
Name: Price, Length: 818, dtype: int32

In [73]:
df['fuel_type'] = df.apply(lambda row: row['kms_driven'] if row['kms_driven'] == 'Petrol' else row['fuel_type'], axis=1)
df['kms_driven'] = df['kms_driven'].astype(str).str.replace('Petrol', '', regex=False)
df.dropna(subset=['fuel_type'], inplace=True)
df

,name,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,2007,80000,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,2006,425000,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,2014,325000,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,2014,575000,"36,000 kms",Diesel
6,Ford Figo,2012,175000,"41,000 kms",Diesel
...,...,...,...,...,...
886,Toyota Corolla Altis,2009,300000,"1,32,000 kms",Petrol
888,Tata Zest XM Diesel,2018,260000,"27,000 kms",Diesel
889,Mahindra Quanto C8,2013,390000,"40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,2014,180000,,Petrol
891,Chevrolet Sail 1.2 LT ABS,2014,160000,,Petrol

In [55]:
df.isnull().sum()

name           0
year           0
Price          0
kms_driven     0
fuel_type     39
dtype: int64

In [79]:
df['kms_driven'] = df['kms_driven'].astype(str).str.replace(' kms','', regex=False)
df['kms_driven'] = df['kms_driven'].astype(str).str.replace(',','', regex=False)

In [ ]:
df['kms_driven'] = df['kms_driven'].replace(['', np.nan], regex=False)
df["kms_driven"].astype(int)

C:\Users\0304f\AppData\Local\Temp\ipykernel_10492\1578670400.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['kms_driven'] = df['kms_driven'].replace(['', np.nan], regex=False)

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890     40000
891     40000
Name: kms_driven, Length: 818, dtype: int32

In [ ]:
X=df.drop(columns="Price")
y=df["Price"]
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3,random_size=42)
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
y_train=ss.fit_transform(y_train)